apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: {{SERVICE_NAME}}:latest
          ports:
            - containerPort: {{SERVICE_PORT}}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health/live
              port: {{SERVICE_PORT}}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health/ready
              port: {{SERVICE_PORT}}
            initialDelaySeconds: 5
