apiVersion: v1
kind: Secret
metadata:
  name: {{SERVICE_NAME}}-secrets
type: Opaque
stringData:
  # Los VALORES los inyecta el banco (K8s Secret / Vault)
  # Aquí solo los NOMBRES de las variables
  SERVICE_NAME: "{{SERVICE_NAME}}"
  SERVICE_PORT: "{{SERVICE_PORT}}"
  # ANTHROPIC_API_KEY: ""
  # OPENAI_API_KEY: ""
  # DATABASE_URL: ""
